### ISSUE TITLE
NdArrayコンストラクタについて提案です

### ISSUE THREAD

**Issue by nyatla** [harujoh/KelpNet#10]
不具合ではありません。提案です。
NdArrayのコンストラクタNdArray(double[] data, int[] shape)についてですが、内部で配列の複製をしています。
まだ完全な調査したわけではありませんが、ほとんどの利用例で複製が必要なのはshapeのみにみえます。

例えばELU#NeedPreviousBackward関数の場合、dataは呼び出し元で新規に割り当てられており、shapeについては他のオブジェクトを参照していました。

不要な再割当を除去する目的で、次の変更を加えてみてはいかがでしょうか。

1. コンストラクタをNdArray(double[] data, int[] shape,bool is_clone)のように変更する。is_cloneはtrueの場合にコンストラクタ内でオブジェクトを複製する。falseの場合は参照してセットする。

2. NdArrayコンストラクタのうち、dataの複製が不要なものを、new NdArray(data,shape.clone(),false)のような呼び出しに変更する。

Kelp.Javaの場合は以下のような実装を行いました。
よろしければ参考にしてください。

https://github.com/nyatla/Kelp.Java/blob/master/src/jp/nyatla/kelpjava/common/NdArray.java#L26

https://github.com/nyatla/Kelp.Java/blob/master/src/jp/nyatla/kelpjava/functions/activations/ReLU.java#L41

**Comment by harujoh** [comment]
nyatlaさんのご指摘はいつも鋭く、私が悩んだ部分に綺麗に突き刺さるので、とても良い刺激になっており、感謝の念に堪えません。
今回ご提案いただいた件についても悩んだことがあり、一つの指針を持っています。

コピーを必要としないインスタンスを作る必要があるのであれば、それは新規作成ではなく変換のメソッドであり、コンストラクタとして望ましい挙動ではないのではないか？という観点から現在はコピーを取る挙動になっております。

その考えに従い最初はコピーを取らないメソッドも実装していたのですが、ケースバイケースで使い分けをしていくと可読性が悪かったため削除した覚えがあります。

しかし、現状では速度がほしいユースケースも有り、このメソッドを復活させる方向で対応させていただきたいと思います。

**Comment by nyatla** [comment]
お返事ありがとうございます。

設計思想の違いが出る部分なのでどれが正しいというのはありませんが、私は複製はコール元責任で、所有権を移譲する、または共有するという解釈で参照渡しにする実装が好みです。

理由は、引数オブジェクトの複製をコンストラクタ内で処理すると、オブジェクトを共有するか複製するかを、呼び出し元が選択できなくなるためです。（選択の必要が無い場合は内部複製でも構わないと思います。）

Javaで再実装したものについては、複製＝コピーコンストラクタ、（値の移譲を受けて）生成＝コンストラクタで役割分担しました。コンストラクタのis_cloneは一時的に付けた変数で、コール元を全数チェックした後ですべてfalseなら取り除こうと思っています。

追記
書き換え作業必要になったら教えてください。お手伝いできます。

**Comment by harujoh** [comment]
頂きましたアドバイスを私なりの形にはなりますが、取り入れたものをコミットいたしました。
この変更によりパフォーマンスが全体にわたり10％程改善いたしました。ありがとうございました。

また、お手伝いのお申し入れありがとうございます。
しかしながら、この度の変更はコード量もそれほど大きくなく、変更も単調なものでしたので、
そのお気持ちのみ有難く頂戴させていただきます。
