### ISSUE TITLE
lossクラス関連の分離について

### ISSUE THREAD

**Issue by nyatla** [harujoh/KelpNet#12]
不具合報告ではありません。

KelpNetのloss関連の実装についてですが、今はstatic関数とdelegateで実装されています。
Javaに移植する過程で、delegateとpartial classが使えないのでアルゴリズム毎にクラス化することにしました。

https://github.com/nyatla/Kelp.Java/tree/master/src/jp/nyatla/kelpjava/loss

使い勝手はあまり変わりませんが、、気に入っていただけたらKelpNetの方も切り替えていただければと思います。

**Comment by harujoh** [comment]
ご報告ありがとうございます。

『C#特有の記述を極力避けているため』と表で書いておきながら、delegate使ってるのはどうなんだろうなぁと思ってはいたものの、使う分には読めば分かる機能だろうと見て見ぬふりをしていたのですが、移植となるとそうも言っていられませんよね。

partial classも同様にズルい表記だなぁと半ば確信犯なところもありましたが、既存の資産を使いまわしたかったことも有り、そのまま公開していました。

これを機に、ご提示いただいたような仮想クラスもしくはインターフェースを設けて、それを共通の踏み台にしてコールする他の関数群と同じような形に統一しようと思います。

**Comment by harujoh** [comment]
ご提案いただいた内容を参考に delegate および partial class を排除し、言語依存度を下げました。

書式が若干変わってしまいましたが、こちらの方が拡張性がよく、使い勝手に統一感が有りますので、この書式を採用しました。

**Comment by harujoh** [comment]
ご提案いただいた内容を参考に delegate および partial class を排除し、言語依存度を下げました。

こちらの方が拡張性がよく、使い勝手に統一感が有りますので、この書式を採用させて頂きました。

**Comment by nyatla** [comment]
対応ありがとうございます。
