### ISSUE TITLE
MnistDataクラスのメンバ変数の配列構成について質問です。

### ISSUE THREAD

**Issue by nyatla** [harujoh/KelpNet#13]
以下の２変数について、配列の構造に疑問があります。
~~~~
        private double[][,,] X;
        private double[][,,] Y;
~~~~
変数は、[N][1,28,28]の配列になっていますが、一番先頭の要素数1が何のためのものかわかりませんでした。
（Mnistのデータ構造を走査するためか、カラーチャンネル？等の意味があるのかなとも思いましたが、今のところよくわかりません。）

この1を削除して二次元配列にすることで、何か問題を引き起こすことはありますか？なければ削除して2次元配列にしてもよいと思います。

また、以下の２変数についても同様に一時配列でよいと思います。
~~~~
        private int[][] Tx;
        private int[][] Ty;
~~~~

**Comment by harujoh** [comment]
お察しの通りカラーチャンネルとしてConv2D内でシェイプを見て判定しており、そのために用意された要素数です。
なので、Conv2Dの入力に合わせるための手抜きの処置と思っていただいて良さそうです。
また、Tx,Tyについても同様にLoss関数に入力する際に配列であると便が良いため、このような実装になっています。

この部分はオマケ感覚で動作することを優先して移植しており、実装がいい加減であることは否めませんね……。
ただ、ベストな状態ではありませんが、悪い状態でも無く、優先度もそれほど高くないため、現時点ではそのままにしておきたいと思います。

**Comment by nyatla** [comment]
保留の件、了解しました！

ローカルで修正を試みたのですが、確かにloss関数周りの実装と噛み合いませんでした。

まだ修正はできていないのですが、参考として修正したパッチまでは仕上げてみようと思います。
（プルリクエストはしません）

本題とは外れますが、Trainerクラスの以下の関数でちょっと気がかりなことがあります。
~~~~
       public static double Train(FunctionStack functionStack, Array input, Array teach, ILossFunction lossFunction, bool isUpdate = true)
~~~~
と
~~~~
public static double Train(FunctionStack functionStack, Array[] input, Array[] teach, ILossFunction lossFunction, bool isUpdate = true)
~~~~
についてですが、引数として多次元配列を引き渡した場合に、呼び出される関数に混乱があるように見えます。
具体的には、input=double[][]とteach=double[]を引き渡した場合に、後者が選択されずに前者が選択されることがありました。
この例では当然そうなることは予測できるのですが、問題に感じるのはArrayがArray[]とArrayを区別できない点です。
やや面倒ですが、train関数は数値型ごとに次元数を固定した関数をオーバロードしたほうがよいかもしれません。
