### ISSUE TITLE
MnistDataの新しい構造について提案があります。

### ISSUE THREAD

**Issue by nyatla** [harujoh/KelpNet#15]
#13 で取り上げたMnistDataの配列構造についてです。

MnistData周りを再実装して問題を解決するというアプローチなのですが、MnistDataの提供する画像/ラベルデータを、MnistDataクラス内でKelpNetに適したNdArrayにまで加工してしまうことで、解決できそうです。

現状のMinstDataはデータ構造を反映したメンバ変数を保持していて、これをArrayやint[][]等に変換してアプリケーションに引き渡しています。アプリケーション側はそれらのデータをKelpNetにそのまま入力するため、KelpNetにはArray-NdArray変換などの本来不要な処理が必要です。また、アプリケーションは中間形式の配列構造を意識しなければなりません。

MinstDataが提供するデータをKelpNetにそのまま入力可能なNdArrayまで加工してしまうことで、KelpNet側のArray-NdArray変換処理を削除することができ、また、アプリケーションやKelpNet本体からMnistDataのデータ構造を隠ぺいすることができます。

このためには、KelpNetにNdArrayを入力するAPIを新たに作らなければなりませんが（以前はあった気がします）、元々内部処理はNdArrayベースでされているので大きな負担はないと思います。

#14 で述べられていたように、今後Arrayを廃止するのであれば、KelpNetへの入力フォーマットはNdArrayに統一し、各種のデータからのNdArrayへの変換責務はアプリケーションやデータIOクラスに任せたほうが、構造的にすっきりするように思います。

Javaでの実装は既にありますので、よろしければC#のパッチを作成してコードを寄贈します。

Javaでの実装例は、

MnistDataの読み取り部分が
https://github.com/nyatla/Kelp.Java/tree/master/src/jp/nyatla/kelpjava/io
使用例が
https://github.com/nyatla/Kelp.Java/blob/master/src.test/jp/nyatla/kelpjava/test/Test4.java#L36

です。

本題とは関係ありませんが、RandomにXorShiftを使ってみてはいかがでしょうか。移植の際に乱数ジェネレータに差異があったので実装したものですが、処理系で値が変わらないのは便利ですよ。
https://github.com/nyatla/Kelp.Java/blob/master/src/jp/nyatla/kelpjava/common/XorShift31Rand.java

**Comment by harujoh** [comment]
これについても悩んだ部分でして、部品を本体に依存した作りにすれば、スマートにはなるのですが、それは部品ではなくKelpNetの付属品になってしまい、他で使いまわしが効かなくなってしまうとの考えで、現在の妙な実装になっています。

ですので、寄贈については、あまりにもったいないお言葉ですが、謹んで辞退を申し上げます。


乱数については一時期メルセンヌツイスタを使っていたのですが、結果にさほど影響なく、配列参照よりも高速で値が返ってくる利点がある為.Netの標準の乱数を採用しました。

しかし『処理系で値が変わらない』という点は確かに魅力的です。
ただ XorShift にはいくつか苦い思い出があり、使うのであればメルセンヌツイスタを使おうかと思っています。

**Comment by harujoh** [comment]
先のコメントを読み直していて矛盾に気が付きました。

先に述べた視点を順守するのであれば、現在のMnistDataのデータ構造が用途に対し完全に独立していないのは、おかしいです。

なので対応方法としてはシンプルに、こちらの方向性で修正したいと思います。
https://github.com/harujoh/KelpNet/issues/13


内情をお話ししますと、こちらのMnistDataを３つのライブラリのテストで使いまわしてきた経歴があり、なんとなくそのままにしておきたいなぁという気持ちの温床になっていました。せっかくですので、この機会にほかのライブラリも直していきたいと思います。

**Comment by nyatla** [comment]
余計な指摘ばかりですみません。
現在の実装の理由について、了解です。

経験談になりますが、データパーサー等は使いまわしすると、結局は組みなおすことになる場合が多いので、”そのクラスだけコピペすれば動く”レベルの独立性が使い勝手が一番使いやすいと思います。

少し面倒ですが、ファイルから基本的なデータ構造に変換する部分と、そのデータをライブラリやアプリケーションで使う形式に成型する部分の２本立てで構成して、前者をC#の場合はフレームワークの用意する関数しか使わないなどの制約で実装し、後者をライブラリごとに作り直すのが一番利便性が良かったです。

**Comment by harujoh** [comment]
MNISTのデータの取り回しを変更いたしました。

対応方法は、検討いたしました結果、このツリーでご提案いただいた形での実装になっております。
