### ISSUE TITLE
BatchNormalizationの分割について

### ISSUE THREAD

**Issue by nyatla** [harujoh/KelpNet#16]
改善提案です。

BatchNormalizationクラスについてですが、学習ありと学習なしが同一クラスに実装されているために見通しが悪くなっているように見えます。

共通部分が多いので１つのクラスにまとめたものと思われますが、BatchNormalizationWithoutTrainとBatchNormalizationのように、２つのクラスに分けてみてはいかがでしょうか。

IsTrainの分岐が削除できると、いくつかのメンバ変数が削除できて、全体の見通しが良くなると思います。

**Comment by harujoh** [comment]
ご提案ありがとうございます。
たしかに、ご指摘頂いたとおりの状態になっており、改善策も基本的にはご提案いただいた方向性で良さそうです。

ただ、BatchNormalizationWithoutTrainを素直に実装し、そのまま表に出してしまうと、今後他の関数でも同様のWithout～の増殖を招いてしまい、また同じロジックを分割したクラスにすることで、メンテナンス性の低下も懸念されます。

なので、そのあたりに折り合いのつく実装を模索したいと思います。

**Comment by nyatla** [comment]
そのあたりは確かにトレードオフになりますね。クラスを分割する基準は、パフォーマンス改善が明らかな場合（多重ループ中のバイトコードが減るとか、性能テストで明らかに速度向上が認められる場合）か、分割しようとする機能が明確に異なる場合に限定するべきです。

例えばIsParallelの分岐などは、パフォーマンス改善が明らかなので、XXXX_O1などのクラスを新規に起こしてもよいと思います。逆にbiasの有無でクラスを分割するのは、パフォーマンス上のメリットが期待できなそうなので、必要ないと思います。


メンテナンス性についての懸念は確かにありますが、構造が単純になるぶん、同一コードを無理に共有するよりも、妙なミス（部分的な修正忘れなど）が減ることは期待できるかもしれません。実装量が増えて面倒くさいのはありますが…。

以上、利点だけになりましたが、参考になれば利用してください。

**Comment by harujoh** [comment]
こちらについての対応ですが、申し訳ありませんがリジェクトとさせて下さい。

理由としては、WithTrain と WithOutTrain と言う形での分離ができなかった点が挙げられます。
また、先の返信にも書きましたが、メンテナンス性への影響がやはり気がかりです。

コードの見通しの悪さについては、現在の実装の甘さに依るところもあり、クラスそのものの分割ではなくメソッド化での対応を模索していきたいと考えております。
