### ISSUE TITLE
Test9の64行目付近、int txにEOSが２回入力される件について

### ISSUE THREAD

**Issue by nyatla** [harujoh/KelpNet#18]
Test9.csについて、想定通りの動作なのか教えてください。

64行目付近、int txは、文字列id[i+1]の文字列を受け取る変数ですが、末端まで到達したとき、強制的にEOSがセットされるようになっています。

末端の文字列idは常にEOSであるので、ネットワークにはEOSが２回入力されてしまいますが、これは想定した動作でしょうか？

**Comment by harujoh** [comment]
実は私もその是非を理解しきっていないのですが、元としている書籍の挙動に合わせたというのが正直なところです。

私の淡い理解と、想像を超えないのでこんな感じかな？というフワッとした話になりますが、持論を展開します。

少し乱暴に言えば『RNNは過去に入力された値から未来の値を予測する関数だ』という事しましょう。
従ってEOSの次はEOSと学習することは間違っていないように思えます。

仮に何らかの文を出力していった時に、予測された次のキーワードがEOSになった場合、その次に何かの文字列を出力するとしたら、もう既に文は終わっているのだから残りがEOS、EOS、EOSで埋まる挙動は間違っていないようにも思えます。

そういう考え方でいくと、行末を機械的に全てEOSにすることのほうが間違っていると言えなくもないかなと思いますが、入門書なのでそのへんは端折ってあるのかな？ぐらいに考えています。

**Comment by nyatla** [comment]
解説ありがとうございます。
確かに、EOS以降にEOSが無限に続く解釈は正しく見えます。
修正した内容を見ましたが、空行の入力がなければ問題はなさそうです。
