### ISSUE TITLE
Convolution2Dクラスの最適化について

### ISSUE THREAD

**Issue by nyatla** [harujoh/KelpNet#19]
KelpJavaでの話ですが、Convolution2Dの最適化をしてみました。
パフォーマンス計測はしていませんが、ループ最深部のバイトコードが減ってるので多分早いと思います。

https://github.com/nyatla/KelpJava/blob/master/src/jp/nyatla/kelpjava/functions/connections/Convolution2D_O1.java

変更点は関数内だけで完結しているので、C#への移植は難しくありません。
可読性は悪くなるので、元のコードといつでも切り替えられるように実装するとよいと思います。

最適化のポイントは以下の通りです。
- ループ深部のif文の削除(計算対象のインデクスの事前計算)
- メンバ変数アクセスをローカル変数に変更(バイトコードの削減)

**Comment by harujoh** [comment]
返信遅くなりまして申し訳ありません。

現在、本職が架橋に入っており中身の検証に少しお時間を頂きたいと思います。
ご対応、誠にありがとうございました。
