### ISSUE TITLE
Waifu2x example is not working.

### ISSUE THREAD

**Issue by gmlwns2000** [harujoh/KelpNet#23]
The program is crashing at `DynamicJsom:257` with `System.InvalidCastException (Cannot convert Double to KelpNet.Common.Real)`. And I changed it to `return (Real)(double)value;` when `elementType` is `Real` like [this](https://github.com/Kawaian/KelpNet/blob/ce5e87c77af6e328d252d3978b51433d8fdf9275/KelpNetWaifu2x/DynamicJson.cs#L259).

After then, the program makes another problem in `FormMain:61`. In the program, it said just ignore errors, but if then all data indexing skipped. So I fixed it to like [this](https://github.com/Kawaian/KelpNet/blob/ce5e87c77af6e328d252d3978b51433d8fdf9275/KelpNetWaifu2x/FormMain.cs#L53)

And then, it has still problem in indexing too. Some of conv weight data formatted into `[preCh, nextCh, kW, kH]`, not `[nextCh, preCh, kW, kH]`. So I just right some hard code patches like [this](https://github.com/Kawaian/KelpNet/blob/ce5e87c77af6e328d252d3978b51433d8fdf9275/KelpNetWaifu2x/FormMain.cs#L63)

After all, result images are wrong. It produced just some glitched images.
I have no idea my model json is wrong or program is wrong.

**Comment by harujoh** [comment]
I appreciate your trouble report :)
Perhaps there is a problem with the program.

This project has been neglected for a long time and maintenance has not been adequate.
I will organize as soon as other priorities are settled.


あなたの不具合報告に感謝いたします。
恐らくプログラムに問題が発生していると思われます

このプロジェクトは長い間放置されており、メンテナンスが行き届いていませんでした。
他の優先事項が片付き次第、整理を行いたいと思います。

**Comment by gmlwns2000** [comment]
Thank you for response it :3

Then I will waiting for it is updated.

**Comment by harujoh** [comment]
Move to other repository.
