### ISSUE TITLE
Weight initializer is slow

### ISSUE THREAD

**Issue by gmlwns2000** [harujoh/KelpNet#24]
Any idea of optimize it?

[I tried Parallel.For](https://github.com/Kawaian/KelpNet/blob/8f322f3d356a54e4f01d9243bc65bc92d6e7ea8e/KelpNet/Common/Tools/Initializer.cs#L15), it made 2x faster initialize, but 16x more CPU usages... I think C#'s Parallel is not a good idea for parallel computations.

**Comment by harujoh** [comment]
There is currently no plan.

I think that C # Parallel.For is quirky and hard to use


現在、計画にはありません。

C#のParallel.Forは癖があり使いにくいと私も思います。

**Comment by gmlwns2000** [comment]
Ok I got it :3

Then I will considering about this problem later

**Comment by harujoh** [comment]
Delete GetFans Function.

Performance improved  about 2 times.
