### ISSUE TITLE
Linear.Grad is always NULL

### ISSUE THREAD

**Issue by mattcolefla** [harujoh/KelpNet#25]
Linear functions have NULL Grad when testing. Looks like the creation of the gradient object is commented out in all the Linear initialization functions.

**Comment by harujoh** [comment]
I am sorry for the difficulty in understanding how to use KelpNet.
I think that this link will help you to understand.
https://github.com/harujoh/KelpNet/tree/master/KelpNetTester/Tests

KelpNetの使い方がわかりづらくて申し訳ありません。
これを見ていただくと理解の助けになると思います
https://github.com/harujoh/KelpNet/tree/master/KelpNetTester/Tests

**Comment by mattcolefla** [comment]
Sorry, but the serialization error is coming from the tests. It’s the code that I downloaded from your repository.

 

Kind Regards,

Matt R. Cole

 

 <http://www.evolvedaisolutions.com/> www.evolvedaisolutions.com

 <https://www.linkedin.com/in/evolvedai/> https://www.linkedin.com/in/evolvedai/

 <https://github.com/mattcolefla> https://github.com/mattcolefla

 <https://twitter.com/mrc_ai> https://twitter.com/mrc_ai

**Comment by harujoh** [comment]
What number is the problem that is causing the problem?
Looking at the image you reported, it seems that StopWatch is included as a member among the classes you are trying to serialize.

問題が起こっているのは何番のテストですか？
ご報告いただいた画像を見ると、シリアライズしようとしているクラスの中にStopWatchがメンバーとして混入しているように見えます。

**Comment by mattcolefla** [comment]
Test 1

 



 

Kind Regards,

Matt R. Cole

 

 <http://www.evolvedaisolutions.com/> www.evolvedaisolutions.com

 <https://www.linkedin.com/in/evolvedai/> https://www.linkedin.com/in/evolvedai/

 <https://github.com/mattcolefla> https://github.com/mattcolefla

 <https://twitter.com/mrc_ai> https://twitter.com/mrc_ai

**Comment by harujoh** [comment]
StopWatch is not used for test1.
Moreover, it operates without a problem in my PC.

Please check the modified part.
