### ISSUE TITLE
How can this be achieved?

### ISSUE THREAD

**Issue by zcadqewxs** [harujoh/KelpNet#31]
XOR tutorial is like this
X -> [[1,0], [0,1], [0,0], [1,1]]
Y -> [[1], [0], [0], [1]]
-----------------------------------------

I want this, how should I achieve it?

X -> [[1,0,0], [0,1,0], [0,0,1], [1,1,1]]
Y -> [[1,0], [0,1], [0,0], [1,1]]

How to set up FunctionStack?

thank you very much！

**Comment by harujoh** [comment]
It is possible.
I'm very bad named samples is "KelpNetTester".
Your needed is Test1 or Test2.

There is Samples. I hope this will be of some help.
https://github.com/harujoh/KelpNet/tree/master/KelpNetTester
