### ISSUE TITLE
RNN系のテストが失敗する

### ISSUE THREAD

**Issue by prufer-schwi** [harujoh/KelpNet#34]
いつもライブラリ作成お疲れ様です。
既知の問題かもしれませんが、Sample08(LSTMによるSin関数の学習)、Sample10(LSTMによるRNNLM)のサンプルを動かすとBackwardの途中でSystem.ArgumentOutOfRangeExceptionが発生してしまい困っています。

具体的には
SingleInputFunction.cs(25行目)の
NdArray[] xs = PrevInputs[PrevInputs.Count - 1];
でPrevInputs.Countが0のときがありインデックスが-1となりエラーになります。
Sample08は即座に発生し、Sample10は十数分動かすと発生します。
Sample09は30分程度動かした限りは問題なく動いていそうです。

環境依存の問題ではなさそうに思えますがそちらの環境で再現できない場合は動作環境の詳細情報を追記したいと思います。

以上よろしくお願いします。

**Comment by harujoh** [comment]
ご報告いただきありがとうございます。

テストコードにばかり気を取られていてSampleの動作チェックが疎かになっていました。申し訳ありません。

さらに申し訳ないのですが、今週末は出掛けてしまっており、手元に環境がないため再現テストができません。

ご報告いただいた現象から以下のような問題が想像されます。
・Sample08：RNN系の挙動を変えたことで不整合が発生している可能性があります
・Sample10：仕様変更でクリア処理を無くしたことにより、メモリを食いつぶしている可能性があります。

月曜日はすでに別の案件が入っており、ソースコードに触れられるのが火曜日になりそうなので、そこでまた続報をお知らせしたいと思います。

**Comment by harujoh** [comment]
少し時間ができたので解析とパッチを当てました。

このパッチで動作自体はするのですがSample10は学習が進まず、まだ挙動がおかしいように感じますが、内容を詳細に追うまで時間を取れませんでしたので、ここは火曜日以降に回します。
Sample08は正常復帰したように見えます。

原因はRNN系のBackPropにあたり使用済みの値のストア⇔レストアのタイミングが間違っていたのが原因でした。
また先に述べたSample10のメモリですが。全く関係なく、単純にBackPropに差し掛かるまで時間がかかるので落ちるまで時間がかかるだけでした。

**Comment by harujoh** [comment]
Sample10で学習が進まなかったのはLSTMの初期化及びSample10のパラメータの更新方法に問題があったためでした。こちらの修正を適応いたしました。
