### ISSUE TITLE
分岐のあるネットワークの書き方

### ISSUE THREAD

**Issue by yosider** [harujoh/KelpNet#36]
KelpNetで分岐のあるニューラルネットを書くことは可能でしょうか．
FunctionStackの代わりにFunctionDictionaryというものを使えば書けるのでしょうか．
よろしければ簡単なサンプルコードをいただけると大変ありがたいです．
よろしくお願いいたします．

**Comment by harujoh** [comment]
＞KelpNetで分岐のあるニューラルネットを書くことは可能でしょうか．
はい可能です。

＞FunctionStackの代わりにFunctionDictionaryというものを使えば書けるのでしょうか．
ご認識の通りFunctionDictionaryを使うことで実現が可能です。
あるいはSplitという層がありますので、そちらを使って2つのFunctionStackへ分岐することも可能です。
https://github.com/harujoh/KelpNet/blob/master/KelpNet/Common/Functions/Type/SplitFunction.cs

＞よろしければ簡単なサンプルコードをいただけると大変ありがたいです．
誠に申し訳ありませんが、現在KelpNetの大規模改造中のため、あまり余裕がないこともあり、ご要望にお応えすることが難しい状況にあります。

そのままのサンプルではありませんがSample17のResNetを読み込んだ後の59行目FunctionDictionaryのnnの中身をブレークポイントを置いていただき、覗いていただくことで、ご理解の助けになると思います。
https://github.com/harujoh/KelpNet/blob/master/KelpNet.Sample/Samples/Sample17.cs

**Comment by yosider** [comment]
丁寧なご返信ありがとうございます．
大変勉強になりました．
大規模改造ですか，楽しみにお待ちしております！
