### ISSUE TITLE
How to use kelpNet to Identify containers ID

### ISSUE THREAD

**Issue by ahghygy** [harujoh/KelpNet#38]
Hi guys
I want to use  kelpNet to identify containers ID.

For example :UESU 300246 9
1.how to make data label
2. which module to use
3.how to trainning
4.how to testing
5.how to validate

**Comment by ahghygy** [comment]
Please gvie me some suggestiong. 
thanks

**Comment by harujoh** [comment]
ハウツーだらけになっていますね
Too many "how to".

まず、あなたの理解を示してください。
Show us your understanding first.

そして、何をしたのかを教えてください。
And tell us what you did.

そこで何ができなかったのか、質問してみてください。
Ask the question, what couldn't you do that ?

ここですべてを教えることはとても難しいので、一つ一つ解決していきましょう。
It's very difficult to teach them all here, so let's solve them one by one.

**Comment by ahghygy** [comment]
ok，thanks，I will try it first. then if get some questions, then to ask you.

**Comment by ahghygy** [comment]
close the issue
