### ISSUE TITLE
1D convolution 層を実装するつもりありますか？

### ISSUE THREAD

**Issue by gheyret** [harujoh/KelpNet#42]
素晴らしいライブラリありがとうございました。
ちなみに1D convolution 層を実装するつもりありますか？

**Comment by harujoh** [comment]
まだまだ至らない点の多いライブラリで、お役に立てたのでしたら幸いです。

現在、KelpNetは大きなバージョンアップを控えており、現在はそちらに注力している状態ですので、
新たな関数の実装は今の所予定していません。


ただ1DConvolutionは2DConvolutionとそれほど大きな違いはなく、小改造で作成が可能かと思います。

また使用方法次第ですが、無改造でも2DConvのカーネルサイズをHeightあるいはWidthを1と設定することで目的が達成できる可能性があります。

この時に入力チャンネル方向にも畳み込みたくない場合は、各チャンネルごとに処理を行えば、チャンネル方向もキャンセルできるので、若干速度は落ちるものの工夫次第では1Dが無くても実現可能な場合もあるかとおもいます。

**Comment by gheyret** [comment]
バージョーンアップ楽しみにしています。

1DConvolutionについての説明ありがとうございました。
Pythorchで作った音声認識のモデルをKelpNetでも作ってみたいと思っておりますので、説明通りにやってみます。

**Comment by harujoh** [comment]
モノラルの音声信号であれば縦または横1ドットの、ほそーいモノクロ画像をイメージしていただければよいかと思います。
頑張ってみてください。
