### ISSUE TITLE
Examples using machine comprehension ONNX

### ISSUE THREAD

**Issue by GeorgeS2019** [harujoh/KelpNet#43]
Please provide KelpNet examples demonstrating inferences using the following [ONNX](https://github.com/onnx/models#machine_comprehension)
- [GPT-2](https://github.com/onnx/models/tree/master/text/machine_comprehension/gpt-2)
- [GPT-2-LM-HEAD](https://github.com/onnx/models/blob/master/text/machine_comprehension/gpt-2/model/gpt2-lm-head-10.tar.gz)

**Comment by harujoh** [comment]
Thank you for your request.

I am also very interested in the GPT series and plan to support it in the future.

However, the current KelpNet is based on Chainer and its design is old, so it is not suitable for new initiatives.

For this reason, we are currently working on a major upgrade based on TensorFlow 2.x.

It may take almost a year to complete the upgrade, but we promise to provide GPT-based samples after the upgrade is completed.

**Comment by GeorgeS2019** [comment]
@harujoh 春条
When you have time, I think the community will be interested to understand your plan for the upgrade. 

Currently, there is .NET community plan to "**catch up**" to address the void for lack of sufficient framework to keep up with the "NOW" the new possibilities to make use of ONNX models exportable by e.g. HuggingFace Transformer.

What do you think will be the coordination the .NET community need to contribute? Do you see the need for e.g. Tensorflow.NET (supporting 2.4+), TorchSharp, Seq2SeqSharp, to speed up the "catch up"

> we are currently working on a major upgrade based on TensorFlow 2.x.

Curious what you mean by that. 

Thank you.

**Comment by harujoh** [comment]
@GeorgeS2019
I don't know what community you belong to, but I don't need contributions from other communities.

All of the libraries I'm working on are for my own learning, and I hope the results will be useful to others.

Therefore, I am not interested in the progress or status of other communities, nor do I intend to collaborate with them.

Again, this library is not created for money.
Therefore, there is no deadline and no obligation. It is a library that I am free to make.

If I ask the rest of the community to contribute, then I have a responsibility and an obligation to reward that contribution.
That means giving up this freedom. That's not what I want.


If you are interested in the current development status or the next version, please visit my twitter.
Unfortunately, all I can tell you right now is that the next version will be based on TensoFlow 2.0.

**Comment by GeorgeS2019** [comment]
@harujoh 春条

Everything is COOL :-)

>  the next version will be based on TensoFlow 2.0.

Great !!
