### ISSUE TITLE
sample links have expired

### ISSUE THREAD

**Issue by omomo17** [harujoh/KelpNet#45]
sample links in readme on the first page have expired

[XOR] https://github.com/harujoh/KelpNet/blob/master/KelpNet.Sample/Samples/Sample1.cs 
[CNN] https://github.com/harujoh/KelpNet/blob/master/KelpNet.Sample/Samples/Sample5.cs 
[AlexNet] https://github.com/harujoh/KelpNet/blob/master/KelpNet.Sample/Samples/Sample19.cs 
[VGG] https://github.com/harujoh/KelpNet/blob/master/KelpNet.Sample/Samples/Sample15.cs
[ResNet] https://github.com/harujoh/KelpNet/blob/master/KelpNet.Sample/Samples/Sample17.cs 

their URL should be
"/Samples/" ⇒ "/Sample/"

**Comment by harujoh** [comment]
Thanks for letting me know.

I fixed the broken link.
