### ISSUE TITLE
Such a phenomenal library

### ISSUE THREAD

**Issue by pjsgsy** [harujoh/KelpNet#49]
Hi - This appears to be such a phenomenal library. Sadly, I can find very few people actually using it, and very little documentation or discussion about how to use it. This library would appear to fill a HUGE gap in the c# ecosystem with regards to NN, but without a Wiki or some active discussion space, it seems its uptake is very small. The author did an amazing job putting it all together as far as I can see. I realise English is not his first tongue and perhaps that is part of the issue with regards to people like myself trying to find good examples.  If anyone can suggest any resources for English discussion/examples using the library, that would be much appreciated. I've not found another library that appears to be as complete, or easily implemented. It seems to me that with a few pages on the Wiki, this library use would explode.

**Comment by harujoh** [comment]
Hello @pjsgsy ,

I am truly disappointed that my library is currently quite niche and not widely known. I also feel a keen sense of my own shortcomings in this regard and regret that I have not been able to increase its visibility more effectively.

If you encounter any issues while using the library, please do not hesitate to post them on StackOverflow. You can send the link to your post to my X(Twitter) DM, and I will be more than happy to help you resolve any problems.

I am fully committed to improving this library and making it more accessible and beneficial for everyone. I will continue to work hard to achieve this goal. Your feedback and suggestions are extremely valuable and always welcome. Thank you very much for your support and input.
