### ISSUE TITLE
FunctionStack#optimizers変数とSetOptimizer関数について提案

### ISSUE THREAD

**Issue by nyatla** [harujoh/KelpNet#6]
FunctionStack#optimizers変数とSetOptimizer関数について提案です。

SetOptimizerを廃止し、FunctionStackのコンストラクタとSetOptimizerを統合してはいかがでしょうか。
具体的には、

~~~~
 public FunctionStack(params Function[] functions) 
~~~~
を
~~~~
 public FunctionStack(Function[] functions,Optimizer[] optimizers)  //学習用
 public FunctionStack(params Function[] functions)  //予測用

~~~~
の２つに変更する提案です。

SetOptimizer関数はFunctionStackのコンストラクタの直後で呼び出される使い方をされていますが、他の使い方をしている部分がなさそうです。

動作中にoptimizersを切り替えを許容しているかにもよりますが、もし許容していないならば、コンストラクタで固定してしまったほうが、実装時にSetOptimizerの呼び出し忘れを防ぐことを期待できます。

予測時にはコンストラクタ内でoptimizers変数をnullで固定しても差し支えない？と思いますが、如何でしょうか。

**Comment by harujoh** [comment]
ご提案いただいた内容については私自身もかなり悩んだのですが、現在はOptimizerをコンストラクタへの選択的な引数として採用はしない方針にしています。

FunctionStackを”関数の集まり”として捉えた場合、Optimizerを内包している現状に疑問があり、利便性の面からコンストラクタに組み込んでしまうと、完全な依存関係が出来上がってしまうため、その実装を踏みとどめています。

理想を言えばOptimizerはFunctionから独立しているべきだと私は考えています。
しかしながらSGDを除くOptimizerはパラメータによる初期化が必要であり、この中途半端な依存関係を切り離すのが難しいのが実情です。

従いまして、ご提案いただいた内容は、現状からすれば、ごもっともなご意見ではありますが、採用は見送らせていただきたいと思います。

**Comment by nyatla** [comment]
回答ありがとうございます。

Optimizerの扱いについて、よく理解できました。
SGD以外の部分についてまだコードを追っていませんので、別の方法（Optimizerをきれいに切り離すような）を見つけたらまた提案をさせていただきたいと思います。
