### ISSUE TITLE
Function#parameters変数について提案です

### ISSUE THREAD

**Issue by nyatla** [harujoh/KelpNet#7]
動作の問題ではありません。構造的な提案です。
Function#parameters変数を削除して、abstractなFunction#GetParameters()関数に置き換え、parametersの実体は各継承クラスで宣言するようにしてはいかがでしょうか。

現状でも問題はありませんが、継承クラス実装時にparametersの初期化を強制できません。継承クラス内でparameters変数を所有してabstractな関数でFunctionに提供すれば、parametersの生成を継承クラスに強制することができます。

paramertersをFunctionのコンストラクタの引数として渡す方法も考えましたが、parametersの生成手段が複雑なので、継承クラスが保持してベースクラスに提供する形がよいと思います。

後ほど具体的なコードをpull requestで示しますので、ご検討をお願いいたします。
（不要でしたらリジェクトしてください。）

**Comment by harujoh** [comment]
ご提案ありがとうございます。

私もこの辺り実は気になっていまして、これに対応したバージョンを手元には作ったのですが（一日に二回仕様変更入れるのはどうなんだ？）という後ろめたさからコミットしていませんでした。

テストも終わってどうしようか迷っていましたが、そちらを適用してみたいと思います。
申し訳ありませんが、もう少しこの仕様変更劇にお付き合い下さい。

**Comment by harujoh** [comment]
私の早とちりで、ご提案いただいた内容とコミットの内容が違うもので申し訳ありませんでした。

ご指摘いただいた内容は『Function』で『Parameters』を保持している事についてですね。
たしかに、ご指摘の通りでFunction内で『OptimiseParameter』と『その実態』の2つで同じ内容を別名でもっており、好ましくない状態であると思われます。

ご提案いただいた関数化について一度試しましたが、傾きを補正するカウンタの扱いが上手くいかず、一度断念いたしました。

現在、ローカルで編集中のものでは、その問題はクリアしましたが、まだ幾つか辻褄の合わないところがあり、もう少しお時間をいただきたいと思います。

**Comment by nyatla** [comment]
ご検討ありがとうございます。
副作用について十分に検証できていなかったようで、申し訳ありません。

仕様変更についてはどんどん進めていただきたいと思いますが、もしバージョン互換性について不安があるのでしたら、Tagを付けて頂ければ（私は）十分です。

**Comment by harujoh** [comment]
ツイッターにも少し書きましたが、ローカルでアレコレと試作してみましたが、分離をすすめると使い勝手が低下していく傾向が見られました。

方向性として、一つのパラメータを一箇所で一つだけ持ち、参照のコピーをあちこちで持たない作りが理想です。
しかし、厳密にこれを行うと、実行時に散らばった値を方々から集めなければならず、可読性、利便性に影響を及ぼすばかりか、速度の低下まで引き起こしはじめる始末で、私の手に負えませんでした。

外部公開しているインターフェース部を巻き戻すことで、かろうじてコミットできるレベルに持っていきましたが、あまり納得できていません。

この件についてはもう一度、ブランチを切って煮詰め直したいと考えています。

**Comment by nyatla** [comment]
了解しました！
このissueは閉じておきますね。
